### ISSUE TITLE
Merging with / using things.py?

### ISSUE THREAD

**Issue by AlexanderWillner** [lmgibson/ThingsStats#1]
Thanks for the code. We might want to discuss whether it makes sense to use [things.py](https://github.com/thingsapi) here and even merge the code. What do you think?

**Comment by lmgibson** [comment]
Hi Alexander,

Thanks for commenting. I went through [things.py](https://github.com/thingsapi), and I think it would be great to discuss using it and merging some functionality into it.

From playing around with things.py, I could pretty easily replicate and extend on this project with things.py because it provides access to more task features than those I am currently using. The only feature that, I believe, is missing is the ability to query tasks within the past X days. 

Would it be okay to add an argument that takes an integer (number of days) and limits the results to tasks created within the last X days? I cloned the repo and added some code that adds a parameter to the get_tasks() method in the Database class that allows for the user to limit results to the past X days.

I'd be happy to submit a pull request. Thanks!

**Comment by AlexanderWillner** [comment]
@mikez thoughts?

**Comment by AlexanderWillner** [comment]
Also: I used to export some statistics at https://github.com/AlexanderWillner/things.sh that I’ve not yet exported to https://github.com/thingsapi/things-cli - so this might be interesting as well.

**Comment by mikez** [comment]
@lmgibson Hey there, Landon! Nice to meet you. :)

I'm a great fan of working together.

> Would it be okay to add an argument that takes an integer (number of days) and limits the results to tasks created within the last X days?

Let's do this!

What do you think about modeling it after pandas' [Dataframe.last](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.last.html)?

The API could be something akin to:
```
things.last("5d")
```
which means "Find all tasks created within the last 5 days". We might only support "d" for now. 

The `things.api.last` function would call to `things.api.tasks` which would pass a parameter to `things.database.Database.get_tasks` as you suggested.

Or... what do you think?

**Comment by lmgibson** [comment]
@mikez Great to meet you too!

I like the idea of modeling it after Dataframe.last. My first instinct, however, was a little different. I was thinking of directly including "last" as a parameter in `things.database.Database.get_tasks()` so that it could be accessed by any of the methods in `things.api` that use `get_tasks()`. For example, one could call things.tasks(last="10d", . . .) to obtain a list of tasks within the last 10 days. 

The implementation would be to add a function to Database.py, `make_date_filter`, that takes the "last" parameter and converts it to the appropriate SQL line to be inserted into the `where_predicate` string.

What do you think of that approach?

**Comment by mikez** [comment]
@lmgibson Wonderful! Sounds great to me. 👌

To clarify: The `things.last()` that I had in mind would be a convenience method which calls `things.tasks(last=..., **kwargs)`. Not very important though, just syntactic sugar. :)

**Comment by mikez** [comment]
@lmgibson Your changes have been merged in and uploaded to PyPI. ✨
You can now use `things.last("30d")` and the like for your project.
